baseURL = 'https://reservefood.org'
languageCode = 'en-us'
title = 'Reserve Food'

[sitemap]
changefreq = 'weekly'
priority = 0.5
filename = 'sitemap.xml'

[params]
description = 'Long-life nutrition infrastructure'

[params.analytics]
plausibleDomain = 'reservefood.org'

[menu]
[[menu.main]]
name = 'About'
url = '/about/'
weight = 10

[[menu.main]]
name = 'Product'
url = '/product/'
weight = 20

[[menu.main]]
name = 'Programs'
url = '/programs/'
weight = 30

[[menu.main]]
name = 'Governments & NGOs'
url = '/governments-ngos/'
weight = 40

[[menu.main]]
name = 'Investors'
url = '/investors/'
weight = 50

[[menu.main]]
name = 'FAQ'
url = '/faq/'
weight = 60

[[menu.main]]
name = 'Contact'
url = '/contact/'
weight = 70
